import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AJR Windows",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-primary ${inter.className}`}>
        <NextTopLoader color="#d4c780" height={2} showSpinner={false} />
        <main className="overflow-x-hidden">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
